import React, { useEffect, useState } from 'react';

const nav = [
  ['dash-definicao','O que é'],['dash-aplicacoes','Aplicações'],['dash-tipos','Tipos de solução'],['dash-briefing','Briefing'],
  ['dash-diagnostico','Diagnóstico'],['dash-escopo','Escopo'],['dash-prazos','Prazos'],['dash-riscos','Riscos'],
  ['dash-fluxo','Fluxo'],['dash-validacao','Validação'],['dash-correcoes','Correções'],['dash-manutencao','Manutenção'],['dash-formulario','Formulário']
];

const dependencies = ['Objetivo bem definido','Indicadores claros','Fontes de dados disponíveis','Regras de cálculo validadas','Qualidade e atualização dos dados','Responsável pela validação','Ferramenta de visualização','Processo de manutenção'];
const applications = ['Acompanhamento de mídia paga','Resultados de redes sociais','Análise comercial e de vendas','Monitoramento de leads','Acompanhamento de CRM','Indicadores financeiros','Performance de campanhas','Resultados de clientes','Indicadores operacionais','Acompanhamento de metas','Consolidação de dados de diferentes plataformas','Relatórios gerenciais e executivos'];

const solutionTypes = [
  { small:'Tipo 01', title:'Dashboard simples', description:'Utiliza uma fonte de dados já organizada, com indicadores e regras de cálculo definidos.', items:['Planilha estruturada','Relatório exportado','Tabela pronta','Conector nativo disponível','Poucos filtros','Baixa complexidade de cálculo'] },
  { small:'Tipo 02', title:'Dashboard integrado', description:'Consome dados diretamente de uma ou mais plataformas.', items:['Meta Ads','Google Ads','GA4','CRM','ERP','Reportei','Banco de dados','API','Webhook','Ferramenta interna'], note:'Pode exigir configuração de acessos, conectores, autenticação, mapeamento de campos e testes de atualização.' },
  { small:'Tipo 03', title:'Dashboard com tratamento de dados', description:'Exige limpeza, padronização, combinação ou transformação das informações antes da visualização.', items:['Nomes diferentes para o mesmo cliente','Datas em formatos incompatíveis','Duplicidade de registros','Ausência de identificadores','Junção de várias planilhas','Indicadores calculados','Histórico fragmentado','Necessidade de criar uma base consolidada'] },
  { small:'Tipo 04', title:'Dashboard com estrutura de dados própria', description:'Exige criação ou adaptação de uma estrutura técnica para coletar, processar e armazenar dados.', items:['Banco de dados','ETL ou ELT','APIs','Jobs agendados','Automações','Armazenamento em nuvem','Controle de histórico','Autenticação','Monitoramento','Tratamento de falhas'], note:'Essa modalidade possui escopo, prazo, infraestrutura e custos próprios.' }
];

const briefingItems = [
  { eyebrow:'01', kicker:'Objetivo', title:'Qual decisão ou acompanhamento o dashboard deve apoiar?', badge:'Obrigatório', tone:'required', description:'O objetivo precisa ser descrito de forma clara.', items:['Acompanhar resultados mensais dos clientes','Comparar investimento e retorno de campanhas','Monitorar leads por origem','Acompanhar funil comercial','Identificar queda de desempenho','Consolidar indicadores de diferentes plataformas','Substituir relatórios manuais','Apoiar reuniões gerenciais'], note:'Um dashboard sem objetivo definido tende a acumular gráficos sem utilidade prática.' },
  { eyebrow:'02', kicker:'Público e usuários', title:'Quem utilizará o dashboard?', badge:'Obrigatório', tone:'required', description:'Defina quem irá visualizar, analisar ou administrar as informações.', items:['Equipe interna','Analistas','Gestores','Diretoria','Cliente','Equipe comercial','Operação','Financeiro','Usuários externos'], note:'Também deve ser definido quem pode visualizar, editar e compartilhar, se há dados restritos e se cada cliente vê somente seus próprios dados.' },
  { eyebrow:'03', kicker:'Indicadores', title:'O que precisa ser acompanhado?', badge:'Obrigatório', tone:'required', description:'Liste todos os indicadores esperados e a finalidade de cada um.', items:['Investimento','Alcance','Impressões','Cliques','CTR','CPC','CPM','Leads','CPL','Vendas','Receita','Ticket médio','Taxa de conversão','Oportunidades','Custo por aquisição','ROI','Meta','Realizado','Variação percentual'], example:'Para cada indicador: nome, significado, fórmula, fonte, periodicidade, filtros aplicáveis, regra de arredondamento, tratamento de valores ausentes e responsável pela validação.', note:'O nome da métrica não substitui sua regra de cálculo.' },
  { eyebrow:'04', kicker:'Regras de negócio', title:'Como os resultados devem ser calculados?', badge:'Obrigatório', tone:'required', description:'As regras de negócio precisam ser validadas antes da conclusão do dashboard.', items:['O que é considerado um lead','Qual data define uma venda','Como identificar um cliente ativo','Como calcular conversão','Como tratar cancelamentos','Quais status entram no funil','Quais registros devem ser excluídos','Como calcular metas','Como combinar dados de fontes diferentes','Qual moeda será utilizada','Qual fuso horário será considerado'], note:'Quando áreas diferentes utilizam definições diferentes para o mesmo indicador, é necessário definir uma regra oficial antes da implementação.' },
  { eyebrow:'05', kicker:'Fontes de dados', title:'De onde virão as informações?', badge:'Obrigatório', tone:'required', description:'Todas as fontes precisam ser listadas.', items:['Google Sheets','Excel','CSV','Banco de dados','BigQuery','PostgreSQL','MySQL','CRM','ERP','Meta Ads','Google Ads','Google Analytics','Reportei','API','Webhook','Plataforma interna','Exportação manual'], example:'Para cada fonte: nome da ferramenta, responsável pelo acesso, tipo de acesso disponível, localização, formato, volume aproximado, histórico disponível, frequência de atualização e limitações conhecidas.' },
  { eyebrow:'06', kicker:'Acessos e credenciais', title:'A equipe possui acesso aos dados?', badge:'Obrigatório antes da integração', tone:'define', description:'Devem ser disponibilizados os acessos necessários para consulta, integração e validação, com as permissões corretas.', items:['Conta da plataforma','Usuário de serviço','Credenciais de API','Chave de acesso','Token','Projeto em nuvem','Banco de dados','Planilha','Documentação','Permissões','Ambiente de teste','Contato do suporte técnico'], note:'Credenciais inválidas, incompletas ou dependentes de terceiros podem impedir o início ou interromper o desenvolvimento. Nunca envie senhas ou tokens em documentos públicos ou canais inadequados.' },
  { eyebrow:'07', kicker:'Qualidade dos dados', title:'Os dados estão organizados e confiáveis?', badge:'Obrigatório para estimativa final', tone:'required', description:'Antes do desenvolvimento, é necessário avaliar a estrutura e a qualidade da base.', items:['Campos disponíveis','Formato das datas','Identificadores','Duplicidades','Valores ausentes','Divergências','Nomenclaturas','Volume','Granularidade','Histórico','Consistência','Frequência de atualização'], example:'Problemas comuns: cliente sem identificador único, campanhas com nomes inconsistentes, planilhas com colunas alteradas, datas como texto e dados manuais sem padrão.', note:'Quando os dados não estão prontos, pode ser necessário criar uma etapa específica de tratamento ou engenharia de dados.' },
  { eyebrow:'08', kicker:'Período e histórico', title:'Qual período o dashboard precisa apresentar?', badge:'Obrigatório', tone:'required', description:'Defina o período e o histórico necessário.', items:['Data inicial','Histórico necessário','Periodicidade','Comparação com período anterior','Comparação anual','Acumulado','Metas mensais','Necessidade de dados retroativos'], note:'Nem toda plataforma disponibiliza histórico ilimitado. A coleta retroativa pode depender de API, exportação manual, limite da ferramenta ou disponibilidade da fonte.' },
  { eyebrow:'09', kicker:'Atualização', title:'Com que frequência o dashboard será atualizado?', badge:'Definir antes da arquitetura final', tone:'define', description:'Quanto maior a frequência, maior pode ser a necessidade de automação, infraestrutura, processamento e monitoramento.', items:['Em tempo real','A cada hora','Diariamente','Semanalmente','Mensalmente','Sob demanda','Por atualização manual'], note:'"Tempo real" deve ser solicitado apenas quando houver necessidade operacional real e suporte técnico das fontes.' },
  { eyebrow:'10', kicker:'Filtros e segmentações', title:'Como os usuários precisam analisar os dados?', badge:'Definir antes do desenvolvimento', tone:'define', description:'Filtros dependem da existência e da qualidade dos campos correspondentes na base.', items:['Período','Cliente','Campanha','Canal','Analista','Unidade','Produto','Região','Status','Vendedor','Origem','Mídia','Tipo de lead'], note:'Não é possível filtrar corretamente por uma informação que não existe ou não está padronizada nos dados.' },
  { eyebrow:'11', kicker:'Estrutura visual', title:'Quais páginas e visualizações serão necessárias?', badge:'Definir antes da implementação', tone:'define', description:'A estrutura visual deve responder às perguntas do negócio, e não apenas reproduzir todos os campos disponíveis.', items:['Visão executiva','Visão geral','Mídia paga','Orgânico','Comercial','Funil','Metas','Detalhamento','Tabela de registros','Comparativos','Página por cliente','Página por unidade'], example:'Também deve ser definido: quantidade de páginas, principais cartões, gráficos, tabelas, rankings, comparações, identidade visual, versão para apresentação e versão para uso operacional.' },
  { eyebrow:'12', kicker:'Ferramenta', title:'Onde o dashboard será desenvolvido?', badge:'Definir antes do desenvolvimento', tone:'define', description:'A escolha depende de fontes de dados, volume, acesso, custo, compartilhamento, atualização, segurança, recursos visuais e infraestrutura existente.', items:['Looker Studio','Power BI','Metabase','Grafana','Plataforma própria','Ferramenta do cliente','Outra solução aprovada'], note:'Licenças, conectores pagos e infraestrutura externa podem gerar custos adicionais.' },
  { eyebrow:'13', kicker:'Compartilhamento', title:'Como o dashboard será disponibilizado?', badge:'Definir antes da publicação', tone:'define', description:'Defina como o acesso será concedido e mantido.', items:['Link público','Link restrito','Acesso por e-mail','Ambiente interno','Conta do cliente','Sistema próprio','Apresentação exportada','PDF','Envio recorrente'], note:'Antes de utilizar link público, deve-se verificar se existem informações confidenciais, dados pessoais ou dados comerciais sensíveis.' },
  { eyebrow:'14', kicker:'Exportação e envio', title:'Será necessário exportar ou enviar relatórios?', badge:'Opcional', tone:'optional', description:'Defina o formato e a recorrência do envio, quando aplicável.', items:['Exportação em PDF','Exportação em Excel ou CSV','Envio por e-mail','Envio por WhatsApp','Relatório automático','Captura de telas','Apresentação mensal','Geração de arquivo por cliente'], note:'Automação de envio, geração de arquivos e distribuição recorrente possuem escopo próprio.' },
  { eyebrow:'15', kicker:'Segurança', title:'O dashboard possui dados sensíveis?', badge:'Obrigatório quando aplicável', tone:'define', description:'Avalie o nível de exposição das informações antes da publicação.', items:['Dados pessoais','Dados financeiros','Informações comerciais','Dados de clientes','Dados de funcionários','Informações confidenciais','Controle por perfil','Restrição por cliente','Necessidade de anonimização','Conformidade com a LGPD'], note:'O nível de acesso deve ser compatível com o tipo de informação exibida.' },
  { eyebrow:'16', kicker:'Responsável', title:'Quem aprovará os indicadores e os resultados?', badge:'Obrigatório', tone:'required', description:'Cada dashboard precisa ter um responsável final pela validação.', items:['Confirmar as métricas','Validar as regras de negócio','Comparar os números com as fontes','Avaliar divergências','Aprovar a estrutura','Centralizar ajustes','Autorizar a publicação'], note:'Sem um responsável final, podem ocorrer aprovações conflitantes e alterações sucessivas.' }
];

const quickChecklist = ['Objetivo do dashboard','Público e usuários','Indicadores necessários','Fórmulas e regras de negócio','Fontes de dados','Histórico necessário','Frequência de atualização','Filtros e segmentações','Estrutura de páginas','Ferramenta de visualização','Forma de compartilhamento','Necessidade de exportação','Requisitos de segurança','Acessos disponíveis','Responsável pela validação','Exemplos ou referências','Data desejada para entrega','Dependências externas identificadas'];
const diagnostico = ['Entendimento do objetivo','Inventário das fontes','Conferência dos acessos','Inspeção dos dados','Validação dos indicadores','Identificação de divergências','Avaliação da ferramenta','Estimativa de tratamento','Identificação de dependências','Definição do escopo da primeira versão'];
const escopoIncluido = ['Reunião ou análise inicial','Organização do briefing','Mapeamento de indicadores','Conexão com fontes aprovadas','Preparação básica dos dados','Criação das páginas','Cartões de indicadores','Gráficos','Tabelas','Filtros','Identidade visual','Testes','Validação com a fonte','Publicação','Documentação básica','Orientação de uso'];
const escopoSeparado = ['Correção de dados na plataforma de origem','Digitação ou preenchimento manual de histórico','Criação de CRM ou ERP','Desenvolvimento de API','Criação de banco de dados','Desenvolvimento de ETL','Infraestrutura em nuvem','Sistema de autenticação','Portal próprio','Automação de envio','Manutenção contínua','Suporte a terceiros','Compra de licenças','Conectores pagos','Recuperação de dados antigos','Auditoria completa das fontes','Criação de indicadores não definidos','Novas páginas após aprovação','Treinamento avançado','Documentação técnica detalhada'];

const prazoTiers = [
  { small:'Estrutura básica', title:'Dashboard simples', estimate:'2 a 4 dias úteis', items:['Existe uma única fonte organizada','Os indicadores já estão definidos','Não há integração complexa','Os cálculos são simples','O histórico está disponível','A estrutura possui poucas páginas'] },
  { small:'Com múltiplas fontes', title:'Dashboard integrado', estimate:'5 a 10 dias úteis', items:['Existem várias fontes','É necessário combinar informações','Há conectores, APIs ou bancos','Existem filtros e páginas adicionais','Os indicadores precisam ser validados','Há testes de atualização'] },
  { small:'Com tratamento de dados', title:'Dashboard com preparação de base', estimate:'A partir de 10 dias úteis', items:['Os dados estão desorganizados','Existem duplicidades ou divergências','É necessário padronizar informações','Várias planilhas precisam ser combinadas','Não existe identificador comum','Há necessidade de processar histórico'] },
  { small:'Com engenharia de dados', title:'Dashboard com estrutura técnica própria', estimate:'Prazo definido após diagnóstico técnico', items:['Banco de dados, ETL ou ELT','API e automação','Jobs agendados','Infraestrutura em nuvem','Autenticação e controle de falhas','Armazenamento histórico'] }
];
const conditions = ['Aprovação do briefing','Definição dos indicadores','Validação das regras de negócio','Disponibilização dos acessos','Confirmação das fontes','Definição da ferramenta','Identificação do responsável pela aprovação'];

const risks = {
  'Objetivo':['Objetivo genérico ou indefinido','Ausência de perguntas de negócio','Mudança de finalidade durante o desenvolvimento','Excesso de indicadores sem prioridade'],
  'Dados':['Dados incompletos','Duplicidades','Ausência de identificadores','Histórico indisponível','Formatos inconsistentes','Divergência entre fontes'],
  'Indicadores':['Fórmulas indefinidas','Conceitos diferentes entre áreas','Métricas alteradas após a implementação','Ausência de responsável pela validação'],
  'Acessos':['Credenciais ausentes','Permissões insuficientes','Tokens expirados','Autenticação em duas etapas','Dependência de terceiros'],
  'Integração':['API sem documentação','Limite de requisições','Instabilidade da plataforma','Conector indisponível','Mudanças na fonte'],
  'Volume':['Grande quantidade de registros','Consultas lentas','Limites da ferramenta','Necessidade de agregação','Custos de processamento'],
  'Escopo':['Novas páginas após o início','Novos filtros','Inclusão de fontes','Novas regras de cálculo','Transformação de relatório simples em sistema'],
  'Aprovação':['Retorno demorado','Solicitações conflitantes','Múltiplos aprovadores','Ausência de responsável final'],
  'Segurança':['Necessidade de restringir dados','Compartilhamento público inadequado','Dados pessoais','Exigências de LGPD'],
  'Ferramenta':['Licença indisponível','Recursos insuficientes','Limites de compartilhamento','Conector pago','Dependência de conta do cliente']
};

const flowSteps = ['Receber a demanda','Entender o objetivo','Identificar usuários','Listar indicadores','Validar regras de negócio','Mapear fontes de dados','Solicitar acessos','Analisar qualidade dos dados','Definir ferramenta','Definir páginas e filtros','Aprovar escopo','Conectar fontes','Preparar ou tratar dados','Implementar indicadores','Construir visualizações','Aplicar identidade visual','Testar filtros e navegação','Comparar resultados com as fontes','Validar com o responsável','Realizar ajustes previstos','Publicar','Validar atualização','Documentar orientações','Encerrar ou iniciar manutenção'];
const validacaoChecklist = ['Indicadores conferidos','Fórmulas validadas','Valores comparados com as fontes','Período correto','Fuso horário validado','Filtros funcionando','Páginas organizadas','Gráficos legíveis','Tabelas consistentes','Nomes padronizados','Valores monetários formatados','Percentuais formatados','Dados ausentes tratados','Duplicidades avaliadas','Atualização testada','Permissões verificadas','Compartilhamento validado','Dados sensíveis protegidos','Responsividade avaliada, quando aplicável','Limitações documentadas','Responsável aprovou os números','Dashboard publicado no ambiente correto'];
const validacaoDimensions = [{ small:'01', title:'Validação dos dados', text:'Os números exibidos correspondem às fontes?' },{ small:'02', title:'Validação das regras', text:'Os cálculos representam corretamente o negócio?' },{ small:'03', title:'Validação da visualização', text:'A estrutura permite compreender e utilizar as informações?' }];
const correcaoItems = ['Fórmula diferente da regra validada','Filtro previsto que não funciona','Gráfico com campo incorreto','Erro de exibição','Problema de acesso configurado pela equipe'];
const ajusteItems = ['Novo indicador','Nova página','Nova fonte','Novo filtro','Mudança de fórmula','Novo tipo de usuário','Automação de envio','Integração adicional','Reconstrução da base'];
const manutencaoTriggers = ['A fonte altera campos','Uma API é atualizada','Uma credencial expira','Uma planilha muda de estrutura','Novos indicadores são solicitados','Regras de negócio mudam','Usuários precisam ser adicionados','A ferramenta apresenta falhas','O volume de dados aumenta','Surgem novas fontes','A operação muda'];
const manutencaoDefine = ['Responsável pela manutenção','Canal de suporte','Prazo de atendimento','Rotina de monitoramento','Processo para solicitar alterações','Custo recorrente','Responsabilidade sobre credenciais','Responsabilidade sobre qualidade da fonte'];
const formQuestionGroups = {
  'Sobre o objetivo':['Qual é o objetivo principal do dashboard?','Qual decisão ele deve apoiar?','Quem utilizará as informações?','Com que frequência será utilizado?'],
  'Sobre os indicadores':['Quais indicadores precisam aparecer?','Como cada indicador é calculado?','Existem metas ou comparativos?','Quem validará os números?'],
  'Sobre os dados':['Quais são as fontes?','Os acessos já estão disponíveis?','Existe histórico?','Com que frequência os dados mudam?','Os dados estão organizados?','Existem divergências conhecidas?'],
  'Sobre a estrutura':['Quais páginas são necessárias?','Quais filtros serão utilizados?','Existe uma referência visual?','Será necessário aplicar identidade visual?','O dashboard será acessado por computador, celular ou ambos?'],
  'Sobre a publicação':['Onde o dashboard será disponibilizado?','Quem poderá acessar?','Existem dados sensíveis?','Será necessário exportar ou enviar relatórios?','Existe uma data desejada?','Há alguma dependência externa?']
};
const finalSummary = [
  { label:'Para iniciar', items:['Objetivo definido','Indicadores listados','Regras validadas','Fontes identificadas','Acessos disponíveis','Dados avaliados','Responsável definido'] },
  { label:'Durante o desenvolvimento', items:['Conectar','Tratar','Calcular','Visualizar','Testar','Comparar','Validar'] },
  { label:'Antes de publicar', items:['Números aprovados','Acessos revisados','Atualização testada','Limitações documentadas','Segurança validada'] },
  { label:'Após publicar', items:['Monitorar','Manter acessos','Controlar mudanças','Registrar novos escopos','Revisar a qualidade dos dados'] }
];

function Title({step, title, text}) { return <header className="sys-title"><span>{step}</span><h2>{title}</h2>{text && <p>{text}</p>}</header>; }
function CheckList({items, columns=true}) { return <ul className={`sys-checks ${columns?'columns':''}`}>{items.map(item=><li key={item}><i aria-hidden="true">✓</i>{item}</li>)}</ul>; }
function Note({children, critical=false}) { return <aside className={`sys-note ${critical?'critical':''}`}><span aria-hidden="true">!</span><p>{children}</p></aside>; }
function Section({id, children, className=''}) { return <section id={id} className={`sys-section ${className}`}>{children}</section>; }
function Cards({data}) { return <div className="dash-cards">{data.map(d=><article key={d.title}><small>{d.small}</small><h3>{d.title}</h3>{d.estimate && <strong>{d.estimate}</strong>}{d.description && <p>{d.description}</p>}<CheckList columns={false} items={d.items}/>{d.note && <Note>{d.note}</Note>}</article>)}</div>; }
function BriefCard({d}) { return <article className="requirement-card"><div className="requirement-head"><span className="icon-box">{d.eyebrow}</span><div><small>{d.kicker}</small><h3>{d.title}</h3></div><span className={`badge ${d.tone}`}>{d.badge}</span></div><p>{d.description}</p><ul className="compact-list">{d.items.map(item=><li key={item}><span className="icon">✓</span>{item}</li>)}</ul>{d.example && <p className="example">{d.example}</p>}{d.note && <div className="inline-note"><span className="icon">!</span><p>{d.note}</p></div>}</article>; }
function GroupAccordion({group, items, index}) { return <details defaultOpen={index<2}><summary><span>{String(index+1).padStart(2,'0')}</span><strong>{group}</strong><i>+</i></summary><CheckList columns={false} items={items}/></details>; }

export default function DashboardContent(){
  const [active,setActive]=useState('dash-definicao'); const [menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>{ const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-25% 0px -65%'}); nav.forEach(([id])=>{const el=document.getElementById(id);if(el)observer.observe(el)}); return()=>observer.disconnect(); },[]);
  const goTo=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});setMenuOpen(false)};
  return <div className="content-layout systems-layout">
    <aside className={`sidebar systems-sidebar ${menuOpen?'open':''}`}><div className="sidebar-title"><span>Nesta página</span><button onClick={()=>setMenuOpen(false)} aria-label="Fechar menu">×</button></div><nav>{nav.map(([id,label],i)=><button key={id} className={active===id?'active':''} onClick={()=>goTo(id)}><span>{String(i+1).padStart(2,'0')}</span>{label}</button>)}</nav></aside>
    <button className="mobile-index" onClick={()=>setMenuOpen(true)}>☰ Navegar pelas seções</button>
    <article className="systems-content">
      <Section id="dash-definicao" className="sys-intro"><div className="sys-index">01</div><div><span className="sys-pill">Indicadores, dados e decisão</span><h2>O que é um<br/>dashboard?</h2></div><div className="sys-intro-copy"><p>Um dashboard é uma interface visual utilizada para acompanhar indicadores, resultados e informações relevantes de uma operação, campanha, área ou negócio.</p><p>Ele transforma dados de uma ou mais fontes em gráficos, tabelas, cartões, filtros e comparativos que facilitam a análise e a tomada de decisão. Um dashboard não é apenas um conjunto de gráficos — para funcionar corretamente, depende de:</p><div className="sys-chips">{dependencies.map(x=><span key={x}>{x}</span>)}</div></div></Section>
      <Section className="sys-quote"><span>Princípio fundamental</span><blockquote>Dados disponíveis não significam, necessariamente, dados prontos para análise.</blockquote></Section>
      <Section id="dash-aplicacoes"><Title step="Aplicações" title="Como normalmente usamos" text="Na Yellow Kite, dashboards podem ser utilizados para acompanhamento operacional, análise de desempenho, gestão de campanhas, consolidação de informações e apoio à tomada de decisão."/><ol className="sys-timeline">{applications.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,'0')}</span><strong>{item}</strong></li>)}</ol></Section>
      <Section id="dash-tipos"><Title step="Qual solução será desenvolvida?" title="Tipos de solução" text="O tipo de solução influencia diretamente o escopo, a arquitetura, o prazo, os custos e a necessidade de tratamento dos dados."/><Cards data={solutionTypes}/></Section>
      <Section><Title step="Orientação operacional" title="Antes de iniciar um dashboard" text="O desenvolvimento deve começar somente quando houver clareza mínima sobre o objetivo, os indicadores, as fontes de dados, as regras de negócio e o responsável pela validação."/><Note critical>Iniciar apenas com a solicitação "precisamos de um dashboard" não é suficiente para estimar ou executar corretamente a demanda. Briefing mais completo significa entrega mais rápida — alterações em métricas, filtros, regras de cálculo, fontes ou estrutura dos dados após o início podem gerar retrabalho e exigir reavaliação do prazo.</Note></Section>
      <Section id="dash-briefing"><Title step="O que o briefing precisa ter" title="Briefing e requisitos" text="Os itens abaixo indicam o que bloqueia o início, o que precisa estar definido durante o desenvolvimento e o que pode ser complementado posteriormente."/><div className="legend"><span><i className="required"/>Obrigatório</span><span><i className="define"/>Definir antes de publicar/integrar</span><span><i className="optional"/>Opcional</span></div><div className="requirements">{briefingItems.map(d=><BriefCard d={d} key={d.eyebrow}/>)}</div></Section>
      <section className="quick-check"><div><span className="eyebrow">Checagem rápida</span><h2>Decisões que precisam<br/>estar definidas</h2><p>Use antes de mover o projeto para desenvolvimento.</p></div><div className="check-grid">{quickChecklist.map(item=><label key={item}><input type="checkbox"/><span><span className="icon">✓</span></span>{item}</label>)}</div></section>
      <Section id="dash-diagnostico"><Title step="Diagnóstico inicial" title="O que precisa ser avaliado antes da estimativa" text="A estimativa final deve ser definida após uma análise inicial da demanda. Em demandas mais complexas, o diagnóstico pode ser tratado como uma etapa própria antes do desenvolvimento."/><CheckList items={diagnostico}/></Section>
      <Section id="dash-escopo"><Title step="Escopo da entrega" title="O que normalmente pode fazer parte" text="Conforme a demanda, a entrega pode incluir os itens abaixo. Salvo quando previstos no escopo aprovado, os itens da segunda lista podem exigir estimativa própria."/><div className="sys-compare"><article><small>Escopo padrão</small><h3>Pode fazer parte da entrega</h3><CheckList columns={false} items={escopoIncluido}/></article><article className="accent"><small>Fora do escopo padrão</small><h3>Exige avaliação separada</h3><CheckList columns={false} items={escopoSeparado}/></article></div><Note>Os itens efetivamente incluídos devem constar no escopo aprovado.</Note></Section>
      <Section id="dash-prazos"><Title step="Planejamento e prazos" title="Estimativas por tipo de solução" text="Cada dashboard recebe uma estimativa específica conforme a quantidade de fontes, a qualidade e o volume dos dados, as regras de negócio, as integrações e a estrutura visual."/><Cards data={prazoTiers}/><h3 className="sys-subtitle">O prazo começa somente após</h3><CheckList items={conditions}/><Note critical>Alterações em indicadores, fontes, filtros, páginas, cálculos ou regras após o início podem exigir reavaliação do cronograma.</Note><Note>Esperas por clientes, fornecedores, suporte técnico, liberação de credenciais, correção de dados ou aprovação não contam como tempo produtivo da equipe e podem alterar a data final.</Note></Section>
      <Section id="dash-riscos"><Title step="Riscos e dependências" title="O que pode impactar objetivo, dados, indicadores, acessos, integração, volume, escopo, aprovação, segurança e ferramenta"/><div className="sys-responsibility">{Object.entries(risks).map(([group,items])=><article key={group}><h3>{group}</h3><CheckList columns={false} items={items}/></article>)}</div></Section>
      <Section id="dash-fluxo"><Title step="Visão geral" title="24 etapas. Nenhum atalho crítico." text="Estrutura informativa preparada para receber status de acompanhamento no futuro."/><ol className="sys-timeline">{flowSteps.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,'0')}</span><strong>{item}</strong></li>)}</ol></Section>
      <Section id="dash-validacao"><Title step="Qualidade e validação" title="Checklist técnico antes da apresentação"/><CheckList items={validacaoChecklist}/><h3 className="sys-subtitle">Como aprovar um dashboard</h3><div className="sys-three">{validacaoDimensions.map(d=><article key={d.small}><small>{d.small}</small><h3>{d.title}</h3><p>{d.text}</p></article>)}</div><Note critical>A aprovação visual não substitui a validação dos dados. O dashboard só deve ser considerado concluído após a conferência dos indicadores por um responsável que conheça a operação e as fontes.</Note></Section>
      <Section id="dash-correcoes"><Title step="Correções e alterações de escopo" title="Correção × Ajuste de escopo"/><div className="sys-compare"><article><small>Correção</small><h3>Ajuste de algo implementado em desacordo com o escopo aprovado</h3><CheckList columns={false} items={correcaoItems}/></article><article className="accent"><small>Ajuste de escopo</small><h3>Alteração ou inclusão que não estava prevista na aprovação inicial</h3><CheckList columns={false} items={ajusteItems}/></article></div><Note>Novos escopos precisam ser avaliados antes da execução.</Note></Section>
      <Section id="dash-manutencao"><Title step="Publicação, continuidade e manutenção" title="O que acontece depois da entrega" text="A entrega inicial não significa que a solução permanecerá funcionando indefinidamente sem acompanhamento."/><div className="sys-split"><div><h3>Pode exigir manutenção quando</h3><CheckList columns={false} items={manutencaoTriggers}/></div><div><h3>Quando necessário, deve ser definido</h3><CheckList columns={false} items={manutencaoDefine}/></div></div></Section>
      <Section id="dash-formulario"><Title step="Formulário para abertura da demanda" title="Perguntas para abrir a demanda"/><div className="sys-accordion-grid">{[0,1].map(column=><div className="sys-accordion-column" key={column}>{Object.entries(formQuestionGroups).map(([group,items],i)=>i%2===column&&<GroupAccordion key={group} group={group} items={items} index={i}/>)}</div>)}</div><div className="sys-accordion-mobile">{Object.entries(formQuestionGroups).map(([group,items],i)=><GroupAccordion key={group} group={group} items={items} index={i}/>)}</div></Section>
      <section className="sys-final"><span>Regra principal</span><h2>O desenvolvimento deve começar quando houver informações suficientes para construir a primeira versão sem depender de decisões básicas.</h2><p style={{color:'#3a3a34',fontSize:13,maxWidth:900,marginTop:14}}>Quanto mais claros estiverem os indicadores, as fontes e as regras, mais rápida e previsível será a entrega.</p><div style={{gridTemplateColumns:'repeat(4,1fr)'}}>{finalSummary.map(g=><div key={g.label}><strong style={{display:'block',marginBottom:8,color:'#514600',fontSize:11,textTransform:'uppercase',letterSpacing:'.08em'}}>{g.label}</strong><p>{g.items.join(', ')}.</p></div>)}</div></section>
    </article>
  </div>;
}
