import React, { useEffect, useState } from 'react';

const nav = [
  ['sys-definicao','O que é'],['sys-fluxo','Fluxo'],['sys-atendimento','Atendimento'],['sys-reuniao','Reunião técnica'],
  ['sys-requisitos','Requisitos'],['sys-tecnologia','Tecnologia'],['sys-infra','Infraestrutura'],['sys-documento','Documento'],
  ['sys-aprovacao','Aprovação'],['sys-contrato','Contrato'],['sys-modulos','Módulos'],['sys-prazos','Prazos'],['sys-ux','UX/UI'],
  ['sys-dev','Desenvolvimento'],['sys-testes','Testes'],['sys-homologacao','Homologação'],['sys-publicacao','Publicação'],
  ['sys-suporte','Suporte'],['sys-seguranca','Segurança'],['sys-responsabilidades','Responsabilidades'],['sys-gates','Gates']
];

const process = ['Atendimento inicial','Levantamento de necessidades','Reunião com Tecnologia','Análise técnica','Documento de validação','Revisão do cliente','Aprovação do escopo','Definição contratual','Planejamento técnico','Desenvolvimento','Testes internos','Homologação com o cliente','Correções','Publicação','Suporte e acompanhamento'];
const initialQuestions = ['Qual é o problema principal?','Quem enfrenta esse problema?','Como o processo funciona hoje?','Quais pessoas utilizarão o sistema?','Quais tarefas precisam ser realizadas?','Quais informações precisam ser cadastradas?','Quais resultados o cliente espera?','Existe um sistema atual?','Será necessário migrar informações?','Existem integrações obrigatórias?','Existe uma data crítica para lançamento?','Quem aprovará o projeto?'];
const requirementGroups = {
  'Problema e objetivo':['Problema a resolver','Resultado esperado','Indicadores de sucesso','Manter ou redesenhar o processo atual'],
  'Usuários':['Públicos internos e externos','Perfis e permissões','Ações de visualizar, criar, editar e excluir','Convite, aprovação e recuperação de senha'],
  'Módulos':['Módulos e prioridades','Dependências entre módulos','MVP e entrega por etapas','Evoluções futuras'],
  'Regras de negócio':['Condições e validações','Ações permitidas e bloqueadas','Exceções e confirmações','Históricos e alertas'],
  'Dados':['Dados pessoais ou sensíveis','Retenção e histórico','Importação, exportação e uploads','Formatos e limites'],
  'Integrações':['CRM, WhatsApp e e-mail','Pagamentos e assinatura digital','APIs e webhooks','Sistemas existentes'],
  'Relatórios':['Consultas e filtros','Dashboard e indicadores','Exportação em PDF ou planilha','Perfis autorizados']
};
const architecture = ['Front-end','Back-end','Banco de dados','Autenticação','Armazenamento de arquivos','Cloud e hospedagem','Serviços externos','Monitoramento','Integrações','Ambientes'];
const validationDoc = ['Contexto, problema e objetivo','Usuários, perfis e permissões','Módulos e funcionalidades','Regras e fluxos principais','Integrações e dados armazenados','Relatórios e notificações','Responsabilidades e infraestrutura','Custos recorrentes','Premissas, dependências e limitações','Itens não incluídos','Critérios de aceite','Modelo de entrega e estimativas'];
const devReady = ['Documento aprovado','Contrato definido','Módulos priorizados','Arquitetura e infraestrutura definidas','Responsáveis definidos','Acessos disponíveis','Protótipos aprovados, quando existirem','Critérios de aceite registrados'];
const testing = ['Autenticação e recuperação de senha','Perfis e permissões','Cadastros, edições e exclusões','Filtros, buscas e validações','Regras de negócio','Notificações e integrações','Uploads e relatórios','Responsividade e navegadores','Mensagens de erro e estados vazios','Segurança básica e performance'];
const deployment = ['Homologação concluída','Critérios de aceite aprovados','Dados de produção configurados','Domínio e SSL configurados','Credenciais protegidas','Backups e logs, quando contratados','Acessos administrativos definidos','Integrações de produção testadas','Responsáveis cadastrados','Documentação entregue','Responsabilidades pós-publicação definidas'];
const responsibilities = {
  Atendimento:['Entender a demanda','Reunir informações','Organizar comunicações','Acompanhar aprovações','Evitar promessas sem análise'],
  Tecnologia:['Analisar viabilidade','Definir arquitetura e infraestrutura','Mapear regras','Desenvolver e testar','Documentar decisões'],
  'UX/UI':['Organizar fluxos','Prototipar','Criar interfaces','Validar usabilidade','Manter consistência'],
  Liderança:['Definir contrato e modelo comercial','Validar responsabilidades','Definir suporte e garantias','Aprovar exceções'],
  Cliente:['Fornecer informações e acessos','Revisar e aprovar escopo','Validar regras','Homologar entregas','Cumprir o contrato']
};
const gates = [
  ['Gate 1','Informações suficientes','A demanda pode seguir para Tecnologia?'],['Gate 2','Análise técnica concluída','Existem informações para produzir o documento?'],
  ['Gate 3','Documento aprovado','O escopo foi formalmente aceito?'],['Gate 4','Contrato definido','Condições comerciais e operacionais foram aprovadas?'],
  ['Gate 5','Pronto para desenvolver','Acessos, infraestrutura, módulos e responsáveis estão definidos?'],['Gate 6','Pronto para homologar','Os testes internos foram concluídos?'],
  ['Gate 7','Pronto para publicar','Cliente aprovou e produção está configurada?']
];

function Title({step, title, text}) { return <header className="sys-title"><span>{step}</span><h2>{title}</h2>{text && <p>{text}</p>}</header>; }
function CheckList({items, columns=true}) { return <ul className={`sys-checks ${columns?'columns':''}`}>{items.map(item=><li key={item}><i aria-hidden="true">✓</i>{item}</li>)}</ul>; }
function Note({children, critical=false}) { return <aside className={`sys-note ${critical?'critical':''}`}><span aria-hidden="true">!</span><p>{children}</p></aside>; }
function Section({id, children, className=''}) { return <section id={id} className={`sys-section ${className}`}>{children}</section>; }
function RequirementAccordion({group, items, index}) { return <details defaultOpen={index<2}><summary><span>{String(index+1).padStart(2,'0')}</span><strong>{group}</strong><i>+</i></summary><CheckList columns={false} items={items}/></details>; }

export default function SystemsContent(){
  const [active,setActive]=useState('sys-definicao'); const [menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>{ const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-25% 0px -65%'}); nav.forEach(([id])=>{const el=document.getElementById(id);if(el)observer.observe(el)}); return()=>observer.disconnect(); },[]);
  const goTo=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});setMenuOpen(false)};
  return <div className="content-layout systems-layout">
    <aside className={`sidebar systems-sidebar ${menuOpen?'open':''}`}><div className="sidebar-title"><span>Nesta página</span><button onClick={()=>setMenuOpen(false)} aria-label="Fechar menu">×</button></div><nav>{nav.map(([id,label],i)=><button key={id} className={active===id?'active':''} onClick={()=>goTo(id)}><span>{String(i+1).padStart(2,'0')}</span>{label}</button>)}</nav></aside>
    <button className="mobile-index" onClick={()=>setMenuOpen(true)}>☰ Navegar pelas seções</button>
    <article className="systems-content">
      <Section id="sys-definicao" className="sys-intro"><div className="sys-index">01</div><div><span className="sys-pill">Solução digital baseada em processos e regras</span><h2>O que é um<br/>sistema?</h2></div><div className="sys-intro-copy"><p>Um sistema é uma solução digital criada para organizar processos, armazenar informações, automatizar atividades e permitir que usuários executem tarefas de acordo com regras previamente definidas.</p><p>Diferente de uma Landing Page ou site institucional, normalmente possui usuários, autenticação, permissões, cadastros, banco de dados, integrações, painéis, relatórios, históricos e funcionalidades conectadas.</p><div className="sys-chips">{['Usuários','Permissões','Dados','Regras','Integrações','Relatórios'].map(x=><span key={x}>{x}</span>)}</div></div></Section>
      <Section className="sys-quote"><span>Princípio fundamental</span><blockquote>Um sistema não começa pelo código. Começa pela compreensão do problema, definição das regras e aprovação do escopo.</blockquote></Section>
      <Section><Title step="Comparativo" title="Site institucional × Sistema"/><div className="sys-compare"><article><small>Site institucional</small><h3>Apresenta informações</h3><CheckList columns={false} items={['Apresenta a empresa','Organiza conteúdo público','Páginas informativas','Direciona para contato','Pouca ou nenhuma regra de negócio','Formulários e integrações simples']}/></article><article className="accent"><small>Sistema</small><h3>Executa processos</h3><CheckList columns={false} items={['Usuários e permissões','Manipulação de dados','Regras de negócio','Diferentes módulos','Banco de dados e integrações','Testes e manutenção contínua','Custos de infraestrutura']}/></article></div><p className="sys-conclusion">Um site apresenta informações. <strong>Um sistema permite que pessoas executem processos.</strong></p></Section>
      <Section id="sys-fluxo"><Title step="Visão geral" title="15 etapas. Nenhum atalho crítico." text="O fluxo organiza decisões, responsabilidades e aprovações desde a primeira conversa até o acompanhamento pós-entrega."/><ol className="sys-timeline">{process.map((item,i)=><li key={item}><span>{String(i+1).padStart(2,'0')}</span><strong>{item}</strong></li>)}</ol></Section>
      <Section id="sys-atendimento"><Title step="01 — Descoberta" title="Atendimento e levantamento inicial" text="O Atendimento entende a necessidade e reúne contexto para Tecnologia, sem definir a solução técnica."/><div className="sys-split"><div><h3>Compreender antes de encaminhar</h3><CheckList columns={false} items={['Problema e processo atual','Pessoas envolvidas','Dificuldades e resultados esperados','Processos a digitalizar','Informações armazenadas','Ferramenta atual','Prazo e orçamento esperados']}/></div><details open><summary>Perguntas iniciais <span>+</span></summary><CheckList items={initialQuestions}/></details></div><Note critical>O Atendimento deve reunir contexto suficiente, mas não deve prometer tecnologia, prazo ou valor sem avaliação técnica.</Note></Section>
      <Section id="sys-reuniao"><Title step="02 — Análise" title="Reunião de análise técnica" text="Transforma a necessidade inicial em uma proposta de funcionamento compreensível e tecnicamente viável."/><div className="sys-three"><article><small>Durante a reunião</small><CheckList columns={false} items={['Identificar usuários e permissões','Mapear módulos e regras','Encontrar exceções','Analisar integrações e riscos','Sugerir arquitetura','Estimar complexidade e dependências']}/></article><article><small>Participantes sugeridos</small><CheckList columns={false} items={['Atendimento','Responsável técnico','UX/UI ou Produto','Liderança, quando necessário','Especialista do cliente']}/></article><article className="accent"><small>Resultado esperado</small><h3>Informações suficientes para produzir o documento de validação de escopo.</h3></article></div><Note>A reunião técnica não é apenas para escolher tecnologia. Ela transforma uma necessidade em regras, módulos e responsabilidades.</Note></Section>
      <Section id="sys-requisitos"><Title step="Checklist central" title="Informações que precisam ser analisadas"/><div className="sys-accordion-grid">{[0,1].map(column=><div className="sys-accordion-column" key={column}>{Object.entries(requirementGroups).map(([group,items],i)=>i%2===column&&<RequirementAccordion key={group} group={group} items={items} index={i}/>)}</div>)}</div><div className="sys-accordion-mobile">{Object.entries(requirementGroups).map(([group,items],i)=><RequirementAccordion key={group} group={group} items={items} index={i}/>)}</div></Section>
      <Section id="sys-tecnologia"><Title step="03 — Decisões técnicas" title="Arquitetura, tecnologia e infraestrutura" text="A escolha depende da análise do projeto; nenhuma tecnologia é padrão obrigatório."/><div className="sys-token-grid sys-token-grid-five">{architecture.map(x=><span key={x}>{x}</span>)}</div><p className="sys-muted">Exemplos possíveis incluem Supabase, PostgreSQL, provedores de cloud e e-mail, APIs, automação, analytics e mensageria.</p></Section>
      <Section id="sys-infra"><Title step="Responsabilidade e custos" title="Quem será responsável pela infraestrutura?" text="Esta decisão precisa estar registrada antes da aprovação final."/><div className="sys-compare"><article><small>Infraestrutura do cliente</small><h3>Contas criadas e mantidas pelo cliente</h3><CheckList columns={false} items={['Quem cria e paga as contas','Acessos fornecidos','Responsável por limites e consumo','Renovação dos serviços']}/></article><article className="accent"><small>Administrada pela Yellow Kite</small><h3>Serviços administrados conforme contrato</h3><CheckList columns={false} items={['Serviços incluídos e cobrança','Limites e aumento de uso','Acompanhamento do consumo','Transferência ao encerrar o contrato']}/></article></div><Note critical>Custos recorrentes de cloud, banco, APIs e serviços externos devem ser informados separadamente do desenvolvimento. A propriedade das contas precisa estar clara.</Note></Section>
      <Section id="sys-documento"><Title step="04 — Referência oficial" title="Documento para validação do cliente" text="Transforma conversas em um escopo verificável, descrito de forma compreensível para o cliente."/><CheckList items={validationDoc}/><Note>O documento de validação é a principal referência entre cliente, Atendimento, Tecnologia e liderança.</Note></Section>
      <Section id="sys-aprovacao"><Title step="05 — Gate de aprovação" title="Aprovação do escopo" text="Enquanto o documento estiver em alteração, o projeto permanece em validação."/><div className="sys-cycle" aria-label="Ciclo de aprovação">{['Documento enviado','Cliente revisa','Solicita alterações','Equipe atualiza','Nova revisão','Escopo aprovado'].map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<5&&<b aria-hidden="true">→</b>}</React.Fragment>)}</div><div className="sys-statuses">{['Assinatura','Aceite no sistema','Aprovação por e-mail','Documento aprovado','Formato validado pela liderança'].map(x=><span key={x}>{x}</span>)}</div><Note critical>O desenvolvimento não deve começar enquanto o documento estiver em processo de alteração.</Note></Section>
      <Section><Title step="Controle de mudança" title="Mudança de escopo" text="Após a aprovação, novas solicitações devem ser avaliadas por impacto técnico, prazo, valor, módulos e documentação."/><div className="sys-token-grid">{['Correção documentada','Ajuste de usabilidade','Melhoria','Nova funcionalidade','Novo módulo','Integração adicional','Alteração estrutural'].map(x=><span key={x}>{x}</span>)}</div><Note>Correção é fazer funcionar conforme o documento aprovado. Nova funcionalidade é ampliar ou modificar o escopo aprovado.</Note></Section>
      <Section id="sys-contrato"><Title step="06 — Liderança" title="Condições definidas com a liderança"/><CheckList items={['Forma de cobrança e modelo de entrega','Cronograma e módulos','Rodadas de ajuste','Garantia, suporte e manutenção','Prioridade, resposta e resolução','Custos e propriedade da infraestrutura','Condições para novas funcionalidades']}/><Note>Prazos de atendimento, correção e suporte devem seguir o contrato aprovado pela liderança.</Note></Section>
      <Section id="sys-modulos"><Title step="07 — Planejamento" title="Implementação completa ou por módulos"/><div className="sys-compare"><article><small>Desenvolvimento completo</small><h3>Um cronograma integrado</h3><p>Indicado para escopo estável, módulos conectados e necessidade da solução completa.</p></article><article className="accent"><small>Desenvolvimento modular</small><h3>Entregas progressivas</h3><p>Indicado para sistemas grandes, prioridades claras, orçamento distribuído ou um MVP.</p></article></div><CheckList items={['Ordem e dependências','Entregáveis','Critérios de aceite','Prazo estimado','Responsáveis','Ambiente de teste','Data de homologação']}/><Note>A escolha deve resultar da análise prévia, não apenas de preferência.</Note></Section>
      <Section id="sys-prazos"><Title step="Estimativas configuráveis" title="Como os prazos devem ser definidos" text="O prazo varia por módulos, regras, perfis, integrações, dados, migração, relatórios, segurança, dependências e aprovações."/><div className="sys-estimate"><div><small>Módulo</small><strong>Descrição a definir</strong></div>{[['Implementação','Prazo a definir'],['Testes internos','Prazo a definir'],['Homologação','Prazo a definir'],['Correções','Conforme complexidade e contrato'],['Publicação','Prazo a definir']].map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</div><Note critical>O prazo de desenvolvimento não deve ser confundido com o prazo total do projeto, que também inclui análise, documentação, aprovação, testes e retorno do cliente.</Note></Section>
      <Section id="sys-ux"><Title step="Etapa quando aplicável" title="Participação de UX/UI" text="A necessidade de prototipação é definida na análise e seu prazo deve ser estimado separadamente."/><CheckList items={['Fluxos e arquitetura de informação','Wireframes e protótipos','Design system','Validação de telas','Testes de usabilidade','Estados, responsividade e acessibilidade']}/><Note>Aprovar fluxo e interface antes do desenvolvimento reduz alterações estruturais durante a implementação.</Note></Section>
      <Section id="sys-dev"><Title step="08 — Execução" title="Implementação"/><h3 className="sys-subtitle">Antes de iniciar</h3><CheckList items={devReady}/><h3 className="sys-subtitle">Durante o desenvolvimento</h3><CheckList items={['Reutilizar componentes','Evitar regras duplicadas','Registrar decisões técnicas','Separar ambientes','Versionar código','Proteger credenciais','Validar permissões','Testar progressivamente','Atualizar status dos módulos']}/><div className="sys-environments"><article><small>01</small><h3>Desenvolvimento</h3><p>Uso da equipe técnica durante a implementação.</p></article><article><small>02</small><h3>Homologação</h3><p>Revisão interna e validação do cliente.</p></article><article><small>03</small><h3>Produção</h3><p>Ambiente oficial dos usuários finais.</p></article></div><Note critical>Testes não devem ocorrer diretamente em produção quando houver risco para dados ou processos reais.</Note></Section>
      <Section id="sys-testes"><Title step="09 — Qualidade" title="Testes internos"/><CheckList items={testing}/><Note>Uma funcionalidade não deve ser considerada concluída apenas porque a tela foi implementada. Cada módulo precisa de critério de aceite.</Note></Section>
      <Section id="sys-homologacao"><Title step="10 — Cliente" title="Validação com o cliente" text="O cliente verifica fluxos, regras, acessos, dados, relatórios, integrações e aderência ao escopo aprovado."/><div className="sys-statuses">{['Erro','Divergência do documento','Ajuste','Melhoria','Nova funcionalidade'].map(x=><span key={x}>{x}</span>)}</div><p className="sys-muted">As ocorrências devem ser registradas de forma organizada e classificadas antes de entrarem no planejamento.</p></Section>
      <Section id="sys-publicacao"><Title step="11 — Go-live" title="Publicação"/><CheckList items={deployment}/><Note critical>Publicar não encerra automaticamente o projeto. O período posterior depende das condições do contrato.</Note></Section>
      <Section id="sys-suporte"><Title step="12 — Pós-entrega" title="O que acontece depois da entrega"/><div className="sys-three"><article><small>Garantia</small><h3>Correção do escopo entregue</h3><p>Duração e condições dependem do contrato.</p></article><article><small>Suporte</small><h3>Dúvidas e incidentes</h3><p>Prazos e canais dependem do contrato.</p></article><article className="accent"><small>Manutenção e evolução</small><h3>Melhorias e novos módulos</h3><p>Tratados conforme o modelo comercial.</p></article></div><Note>Garantia, suporte e evolução são serviços diferentes e precisam estar claramente definidos.</Note></Section>
      <Section id="sys-seguranca"><Title step="Dados e responsabilidade" title="Segurança, privacidade e responsabilidade"/><CheckList items={['Dados armazenados e acessos','Controle de permissões','Proteção de senhas','Dados pessoais e sensíveis','Consentimento e retenção','Backups, logs e auditoria','Exportação e exclusão','Conformidade com a LGPD','Responsabilidade do cliente']}/><Note>Requisitos legais e de conformidade devem ser validados com os responsáveis competentes.</Note></Section>
      <Section id="sys-responsabilidades"><Title step="Matriz operacional" title="Quem faz o quê"/><div className="sys-responsibility">{Object.entries(responsibilities).map(([role,items])=><article key={role}><h3>{role}</h3><CheckList columns={false} items={items}/></article>)}</div></Section>
      <Section id="sys-gates"><Title step="Controle obrigatório" title="Pontos de bloqueio" text="O processo só avança quando o gate anterior possui evidências suficientes."/><div className="sys-gates">{gates.map(([gate,title,text],i)=><article key={gate}><div><small>{gate}</small><span className={i<2?'analysis':'pending'}>{i<2?'em análise':'pendente'}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="sys-statuses"><span>pendente</span><span>em análise</span><span>aguardando cliente</span><span>bloqueado</span><span>aprovado</span><span>concluído</span></div></Section>
      <section className="sys-final"><span>Regra operacional</span><h2>Nenhum sistema deve iniciar com regras essenciais, responsabilidades, infraestrutura ou escopo ainda em negociação.</h2><div><p>O documento aprovado protege o cliente, o Atendimento e a equipe de Tecnologia.</p><p>Quanto mais completo o levantamento, mais previsível será o desenvolvimento.</p><p>Alterações depois da aprovação precisam ser analisadas como mudança de escopo.</p></div></section>
    </article>
  </div>;
}
